{% set name = "bgcArgoDMQC" %}
{% set version = "0.2.13" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/bgcArgoDMQC-{{ version }}.tar.gz
  sha256: d107d761e9284f6a2ec0f38f41addee70d122fd87302f92e4d73e9e9715f3383

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - cmocean
    - gsw
    - matplotlib-base
    - netcdf4
    - numpy
    - pandas
    - python >={{ python_min }}
    - scipy
    - seaborn

test:
  imports:
    - bgcArgoDMQC
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/ArgoCanada/bgcArgoDMQC
  summary: A python library for quality control of BGC-Argo data
  license: MIT
  license_file:
    - LICENSE.txt

extra:
  recipe-maintainers:
    - cgrdn
